image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start MinIO
    init: docker build -t hyper-minio .minio
    command: |
      mkdir -p /workspace/minio/data
      docker run \
        -it \
        -p 9000:9000 \
        -p 9001:9001 \
        -v /workspace/minio/data:/data \
        hyper-minio

  
  - name: Test Harness Environment
    command: |
      export MINIO_URL=`gp url 9000`
      export MINIO_ROOT_USER=minioadmin
      export MINIO_ROOT_PASSWORD=minioadmin

ports:
  # MinIO S3 API
  - port: 9000
    visibility: public
  # MinIO Console
  - port: 9001
    visibility: public
  # hyper
  - port: 6363
    visibility: public
